# Generated by Django 4.2.3 on 2023-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup',
            field=models.CharField(max_length=200),
        ),
    ]
